USE `wedding` ;
DROP TABLE IF EXISTS `wedding`.`fair_zexy_content_details` ;
DROP TABLE IF EXISTS `wedding`.`fair_zexy_contents` ;
DROP TABLE IF EXISTS `wedding`.`fair_zexys` ;
DROP TABLE IF EXISTS `wedding`.`fair_sugukons` ;
DROP TABLE IF EXISTS `wedding`.`fair_rakuten_tokutens` ;
DROP TABLE IF EXISTS `wedding`.`fair_rakuten_contents` ;
DROP TABLE IF EXISTS `wedding`.`fair_rakutens` ;
DROP TABLE IF EXISTS `wedding`.`fair_park_contents` ;
DROP TABLE IF EXISTS `wedding`.`fair_parks` ;
DROP TABLE IF EXISTS `wedding`.`fair_mynavi_contents` ;
DROP TABLE IF EXISTS `wedding`.`fair_mynavis` ;
DROP TABLE IF EXISTS `wedding`.`fair_mwed_contents` ;
DROP TABLE IF EXISTS `wedding`.`fair_mweds` ;
DROP TABLE IF EXISTS `wedding`.`fair_gnavis` ;
DROP TABLE IF EXISTS `wedding`.`fair_dates` ;
DROP TABLE IF EXISTS `wedding`.`fairs`;